INSERT INTO modelos_carro (categoria, descricao, fabricante_id) VALUES
('SEDAN_GRANDE', 'Camry', 1),  -- Toyota
('HATCH_COMPACTO', 'Fit', 2),  -- Honda
('ESPORTIVO', 'Mustang', 3),   -- Ford
('SEDAN_MEDIO', 'Onix', 4),    -- Chevrolet
('UTILITARIO_COMERCIAL', 'NV3500', 5), -- Nissan
('SEDAN_COMPACTO', 'Jetta', 6), -- Volkswagen
('HATCH_MEDIO', 'Elantra', 7), -- Hyundai
('SEDAN_GRANDE', 'Optima', 8), -- Kia
('ESPORTIVO', 'Z4', 9),        -- BMW
('SEDAN_GRANDE', 'S-Class', 10), -- Mercedes-Benz
('HATCH_COMPACTO', 'Yaris', 1),  -- Toyota
('MINIVAN', 'Odyssey', 2),     -- Honda
('UTILITARIO_COMERCIAL', 'Ranger', 3), -- Ford
('HATCH_COMPACTO', 'Tracker', 4), -- Chevrolet
('SEDAN_MEDIO', 'Altima', 5),  -- Nissan
('SEDAN_COMPACTO', 'Virtus', 6), -- Volkswagen
('HATCH_MEDIO', 'Kona', 7),    -- Hyundai
('ESPORTIVO', 'Stinger', 8),   -- Kia
('SEDAN_GRANDE', 'E-Class', 10), -- Mercedes-Benz
('HATCH_MEDIO', 'Corolla', 1), -- Toyota
('MINIVAN', 'Sienna', 2),      -- Honda
('UTILITARIO_COMERCIAL', 'F-150', 3), -- Ford
('HATCH_COMPACTO', 'Sonic', 4), -- Chevrolet
('SEDAN_MEDIO', 'Sentra', 5),  -- Nissan
('SEDAN_COMPACTO', 'Polo', 6), -- Volkswagen
('HATCH_MEDIO', 'Tucson', 7),  -- Hyundai
('ESPORTIVO', 'Stinger', 8),   -- Kia
('SEDAN_GRANDE', 'E-Class', 10); -- Mercedes-Benz
